from __future__ import annotations

from typing import Any, Dict, List


TASK_DATA: Dict[str, Dict[str, Any]] = {
    "upi-scam-triage": {
        "max_steps": 10,
        "time_budget_hours": 3.0,
        "items": [
            {
                "content_id": "upi_1",
                "text": "Congratulations! NPCI lottery ₹50,000 — enter UPI PIN here: bit.ly/win",
                "english_summary": "Prize scam requesting UPI PIN.",
                "content_type": "text",
                "sgi_flag": False,
                "upi_pattern_detected": True,
                "toxicity_score": 0.2,
                "language": "en",
                "timestamp_offset_sec": 0,
                "evidence_signals": ["upi_pin_request", "prize_scam"],
                "account_meta": {
                    "account_age_days": 15,
                    "prior_violations": 3,
                    "payment_linked": False,
                    "verified_badge": False,
                    "country_code": "IN",
                    "posting_frequency_per_day": 1.5,
                },
                "ground_truth_decision": "remove",
                "ground_truth_rule": "IT_2021_3_1_b_iii",
            },
            {
                "content_id": "upi_2",
                "text": "आज Paytm offer hai! ₹500 cashback milega QR code scan karne par 🎉",
                "english_summary": "Suspicious cashback lure with scan QR.",
                "content_type": "text",
                "sgi_flag": False,
                "upi_pattern_detected": True,
                "toxicity_score": 0.1,
                "language": "hi-en",
                "timestamp_offset_sec": 5,
                "evidence_signals": ["qr_swap_pattern", "cashback_lure"],
                "account_meta": {
                    "account_age_days": 6,
                    "prior_violations": 1,
                    "payment_linked": False,
                    "verified_badge": False,
                    "country_code": "IN",
                    "posting_frequency_per_day": 4.1,
                },
                "ground_truth_decision": "remove",
                "ground_truth_rule": "IT_2021_3_1_b_iii",
            },
            {
                "content_id": "upi_3",
                "text": "URGENT: Your SBI UPI is blocked! Call 1800-000-7777 now.",
                "english_summary": "Fake helpline and urgency trigger.",
                "content_type": "text",
                "sgi_flag": False,
                "upi_pattern_detected": True,
                "toxicity_score": 0.3,
                "language": "en",
                "timestamp_offset_sec": 10,
                "evidence_signals": ["fake_helpline", "urgency_trigger"],
                "account_meta": {
                    "account_age_days": 31,
                    "prior_violations": 2,
                    "payment_linked": False,
                    "verified_badge": False,
                    "country_code": "IN",
                    "posting_frequency_per_day": 2.2,
                },
                "ground_truth_decision": "remove",
                "ground_truth_rule": "IT_2021_3_1_b_iii",
            },
            {
                "content_id": "upi_4",
                "text": "Sending payment to @dhobi_press for laundry — ₹150 ✓",
                "english_summary": "Legitimate personal payment confirmation.",
                "content_type": "text",
                "sgi_flag": False,
                "upi_pattern_detected": False,
                "toxicity_score": 0.0,
                "language": "en",
                "timestamp_offset_sec": 15,
                "evidence_signals": [],
                "account_meta": {
                    "account_age_days": 900,
                    "prior_violations": 0,
                    "payment_linked": True,
                    "verified_badge": False,
                    "country_code": "IN",
                    "posting_frequency_per_day": 8.0,
                },
                "ground_truth_decision": "approve",
                "ground_truth_rule": "",
            },
            {
                "content_id": "upi_5",
                "text": "Collect request aayega, bas approve kar dena bhai",
                "english_summary": "Social engineering for fake collect request.",
                "content_type": "text",
                "sgi_flag": False,
                "upi_pattern_detected": True,
                "toxicity_score": 0.1,
                "language": "hi-en",
                "timestamp_offset_sec": 18,
                "evidence_signals": ["fake_collect_request", "social_engineering"],
                "account_meta": {
                    "account_age_days": 7,
                    "prior_violations": 2,
                    "payment_linked": False,
                    "verified_badge": False,
                    "country_code": "IN",
                    "posting_frequency_per_day": 5.4,
                },
                "ground_truth_decision": "remove",
                "ground_truth_rule": "IT_2021_3_1_b_iii",
            },
            {
                "content_id": "upi_6",
                "text": "Screenshot dikhao UPI ka, tabhi refund process hoga.",
                "english_summary": "Screenshot phishing attempt.",
                "content_type": "text",
                "sgi_flag": False,
                "upi_pattern_detected": True,
                "toxicity_score": 0.2,
                "language": "hi-en",
                "timestamp_offset_sec": 20,
                "evidence_signals": ["screenshot_phishing"],
                "account_meta": {
                    "account_age_days": 20,
                    "prior_violations": 1,
                    "payment_linked": False,
                    "verified_badge": False,
                    "country_code": "IN",
                    "posting_frequency_per_day": 3.5,
                },
                "ground_truth_decision": "warn_user",
                "ground_truth_rule": "IT_2021_3_1_b_iii",
            },
            {
                "content_id": "upi_7",
                "text": "Grocery payment received from Sharma ji ✅",
                "english_summary": "Legitimate payment message.",
                "content_type": "text",
                "sgi_flag": False,
                "upi_pattern_detected": False,
                "toxicity_score": 0.0,
                "language": "en",
                "timestamp_offset_sec": 25,
                "evidence_signals": [],
                "account_meta": {
                    "account_age_days": 500,
                    "prior_violations": 0,
                    "payment_linked": True,
                    "verified_badge": False,
                    "country_code": "IN",
                    "posting_frequency_per_day": 6.5,
                },
                "ground_truth_decision": "approve",
                "ground_truth_rule": "",
            },
            {
                "content_id": "upi_8",
                "text": "Verified RazorPay merchant festive sale 20% off, scan to pay",
                "english_summary": "Legitimate merchant promotion.",
                "content_type": "text",
                "sgi_flag": False,
                "upi_pattern_detected": False,
                "toxicity_score": 0.0,
                "language": "en",
                "timestamp_offset_sec": 30,
                "evidence_signals": [],
                "account_meta": {
                    "account_age_days": 1400,
                    "prior_violations": 0,
                    "payment_linked": True,
                    "verified_badge": True,
                    "country_code": "IN",
                    "posting_frequency_per_day": 14.1,
                },
                "ground_truth_decision": "approve",
                "ground_truth_rule": "",
            },
        ],
    },
    "sgi-compliance-review": {
        "max_steps": 8,
        "time_budget_hours": 3.0,
        "items": [
            {
                "content_id": "sgi_1",
                "text": "Video claims politician made inflammatory speech; visual artifacts indicate deepfake.",
                "english_summary": "Undisclosed non-consensual political deepfake.",
                "content_type": "video_desc",
                "sgi_flag": True,
                "upi_pattern_detected": False,
                "toxicity_score": 0.6,
                "language": "en",
                "timestamp_offset_sec": 0,
                "evidence_signals": ["face_artifacts", "identity_impersonation"],
                "account_meta": {
                    "account_age_days": 60,
                    "prior_violations": 2,
                    "payment_linked": False,
                    "verified_badge": False,
                    "country_code": "IN",
                    "posting_frequency_per_day": 0.7,
                },
                "ground_truth_decision": "remove",
                "ground_truth_rule": "IT_2026_SGI_DEEPFAKE",
            },
            {
                "content_id": "sgi_2",
                "text": "AI-generated landscape art #AIArt #MadeWithAI",
                "english_summary": "Disclosed AI art; should be labeled, not removed.",
                "content_type": "image_with_caption",
                "sgi_flag": True,
                "upi_pattern_detected": False,
                "toxicity_score": 0.0,
                "language": "en",
                "timestamp_offset_sec": 5,
                "evidence_signals": ["ai_disclosure_tag"],
                "account_meta": {
                    "account_age_days": 400,
                    "prior_violations": 0,
                    "payment_linked": True,
                    "verified_badge": True,
                    "country_code": "IN",
                    "posting_frequency_per_day": 3.0,
                },
                "ground_truth_decision": "label_sgi",
                "ground_truth_rule": "IT_2026_SGI_LABEL",
            },
            {
                "content_id": "sgi_3",
                "text": "Audio transcript: Beta accident mein hai, ₹15,000 UPI pe bhejo.",
                "english_summary": "Voice-clone financial fraud content.",
                "content_type": "audio_transcript",
                "sgi_flag": True,
                "upi_pattern_detected": True,
                "toxicity_score": 0.4,
                "language": "hi-en",
                "timestamp_offset_sec": 8,
                "evidence_signals": ["voice_clone", "upi_urgent_transfer"],
                "account_meta": {
                    "account_age_days": 22,
                    "prior_violations": 4,
                    "payment_linked": False,
                    "verified_badge": False,
                    "country_code": "IN",
                    "posting_frequency_per_day": 1.0,
                },
                "ground_truth_decision": "remove",
                "ground_truth_rule": "IT_2021_3_1_b_iii",
            },
            {
                "content_id": "sgi_4",
                "text": "Post quoting politician's real speech with commentary overlay.",
                "english_summary": "Legitimate non-SGI political commentary.",
                "content_type": "text",
                "sgi_flag": False,
                "upi_pattern_detected": False,
                "toxicity_score": 0.0,
                "language": "en",
                "timestamp_offset_sec": 13,
                "evidence_signals": [],
                "account_meta": {
                    "account_age_days": 1200,
                    "prior_violations": 0,
                    "payment_linked": True,
                    "verified_badge": True,
                    "country_code": "IN",
                    "posting_frequency_per_day": 10.2,
                },
                "ground_truth_decision": "approve",
                "ground_truth_rule": "",
            },
            {
                "content_id": "sgi_5",
                "text": "AI-generated stock tip: XYZ stock guaranteed 400% returns.",
                "english_summary": "Undisclosed AI financial claim; label required first.",
                "content_type": "text",
                "sgi_flag": True,
                "upi_pattern_detected": False,
                "toxicity_score": 0.2,
                "language": "en",
                "timestamp_offset_sec": 20,
                "evidence_signals": ["undisclosed_ai", "financial_harm_claim"],
                "account_meta": {
                    "account_age_days": 70,
                    "prior_violations": 1,
                    "payment_linked": False,
                    "verified_badge": False,
                    "country_code": "IN",
                    "posting_frequency_per_day": 2.1,
                },
                "ground_truth_decision": "label_sgi",
                "ground_truth_rule": "IT_2026_SGI_LABEL",
            },
            {
                "content_id": "sgi_6",
                "text": "Deepfake celebrity endorsing gambling app with cloned voice.",
                "english_summary": "Commercial deepfake endorsement.",
                "content_type": "video_desc",
                "sgi_flag": True,
                "upi_pattern_detected": False,
                "toxicity_score": 0.5,
                "language": "en",
                "timestamp_offset_sec": 26,
                "evidence_signals": ["celebrity_impersonation", "gambling_promo"],
                "account_meta": {
                    "account_age_days": 16,
                    "prior_violations": 3,
                    "payment_linked": False,
                    "verified_badge": False,
                    "country_code": "IN",
                    "posting_frequency_per_day": 0.9,
                },
                "ground_truth_decision": "remove",
                "ground_truth_rule": "IT_2026_SGI_DEEPFAKE",
            },
        ],
    },
    "cib-graph-takedown": {
        "max_steps": 6,
        "time_budget_hours": 3.0,
        "items": [
            {
                "content_id": "cib_A",
                "text": "Account_A uploads deepfake political video.",
                "english_summary": "Root account in coordinated network.",
                "content_type": "video_desc",
                "sgi_flag": True,
                "upi_pattern_detected": False,
                "toxicity_score": 0.7,
                "language": "en",
                "linked_accounts": ["Account_B", "Account_C", "Account_E"],
                "timestamp_offset_sec": 0,
                "target_account": "Account_A",
                "evidence_signals": ["content_hash_match", "root_origin"],
                "account_meta": {
                    "account_age_days": 62,
                    "prior_violations": 2,
                    "payment_linked": False,
                    "verified_badge": False,
                    "country_code": "PK",
                    "posting_frequency_per_day": 0.3,
                },
                "ground_truth_decision": "remove",
                "ground_truth_rule": "IT_2026_SGI_DEEPFAKE",
            },
            {
                "content_id": "cib_B",
                "text": "Account_B reshares identical video within 28 seconds.",
                "english_summary": "Bot-linked propagation node.",
                "content_type": "text",
                "sgi_flag": True,
                "upi_pattern_detected": False,
                "toxicity_score": 0.4,
                "language": "en",
                "linked_accounts": ["Account_A"],
                "timestamp_offset_sec": 28,
                "target_account": "Account_B",
                "evidence_signals": ["coordinated_window", "bot_pattern"],
                "account_meta": {
                    "account_age_days": 8,
                    "prior_violations": 1,
                    "payment_linked": False,
                    "verified_badge": False,
                    "country_code": "PK",
                    "posting_frequency_per_day": 0.1,
                },
                "ground_truth_decision": "remove",
                "ground_truth_rule": "IT_2026_SGI_DEEPFAKE",
            },
            {
                "content_id": "cib_C",
                "text": "Account_C reshares in 31 seconds with same hash.",
                "english_summary": "Bot-linked propagation node.",
                "content_type": "text",
                "sgi_flag": True,
                "upi_pattern_detected": False,
                "toxicity_score": 0.4,
                "language": "en",
                "linked_accounts": ["Account_A"],
                "timestamp_offset_sec": 31,
                "target_account": "Account_C",
                "evidence_signals": ["coordinated_window", "bot_pattern"],
                "account_meta": {
                    "account_age_days": 12,
                    "prior_violations": 1,
                    "payment_linked": False,
                    "verified_badge": False,
                    "country_code": "PK",
                    "posting_frequency_per_day": 0.1,
                },
                "ground_truth_decision": "remove",
                "ground_truth_rule": "IT_2026_SGI_DEEPFAKE",
            },
            {
                "content_id": "cib_E",
                "text": "Account_E reshares in 29 seconds with same hash.",
                "english_summary": "Bot-linked propagation node.",
                "content_type": "text",
                "sgi_flag": True,
                "upi_pattern_detected": False,
                "toxicity_score": 0.4,
                "language": "en",
                "linked_accounts": ["Account_A"],
                "timestamp_offset_sec": 29,
                "target_account": "Account_E",
                "evidence_signals": ["coordinated_window", "bot_pattern"],
                "account_meta": {
                    "account_age_days": 5,
                    "prior_violations": 1,
                    "payment_linked": False,
                    "verified_badge": False,
                    "country_code": "PK",
                    "posting_frequency_per_day": 0.1,
                },
                "ground_truth_decision": "remove",
                "ground_truth_rule": "IT_2026_SGI_DEEPFAKE",
            },
            {
                "content_id": "cib_D",
                "text": "Account_D shared later from feed organically.",
                "english_summary": "Legitimate user, should not be removed.",
                "content_type": "text",
                "sgi_flag": False,
                "upi_pattern_detected": False,
                "toxicity_score": 0.1,
                "language": "en",
                "linked_accounts": [],
                "timestamp_offset_sec": 45,
                "target_account": "Account_D",
                "evidence_signals": ["organic_distribution", "high_activity_normal"],
                "account_meta": {
                    "account_age_days": 1100,
                    "prior_violations": 0,
                    "payment_linked": True,
                    "verified_badge": False,
                    "country_code": "IN",
                    "posting_frequency_per_day": 12.3,
                },
                "ground_truth_decision": "warn_user",
                "ground_truth_rule": "IT_2026_SGI_LABEL",
            },
            {
                "content_id": "cib_escalate",
                "text": "Network takedown completed. Should escalate formal report.",
                "english_summary": "Final escalation step for government notice trail.",
                "content_type": "text",
                "sgi_flag": False,
                "upi_pattern_detected": False,
                "toxicity_score": 0.0,
                "language": "en",
                "linked_accounts": [],
                "timestamp_offset_sec": 50,
                "target_account": None,
                "evidence_signals": ["cross_border_network", "coordinated_inauthentic_behavior"],
                "account_meta": {
                    "account_age_days": 1,
                    "prior_violations": 0,
                    "payment_linked": False,
                    "verified_badge": True,
                    "country_code": "IN",
                    "posting_frequency_per_day": 0.0,
                },
                "ground_truth_decision": "escalate",
                "ground_truth_rule": "IT_2021_3_1_d",
            },
        ],
    },
    "child-safety-escalation": {
        "max_steps": 4,
        "time_budget_hours": 1.5,
        "items": [
            {
                "content_id": "cs_1",
                "text": "Private channel shares explicit child abuse clip and asks for exchange links.",
                "english_summary": "Urgent child sexual abuse material distribution.",
                "content_type": "video_desc",
                "sgi_flag": False,
                "upi_pattern_detected": False,
                "toxicity_score": 0.95,
                "language": "en",
                "timestamp_offset_sec": 0,
                "evidence_signals": ["minor_exploitation", "csam_distribution"],
                "account_meta": {
                    "account_age_days": 12,
                    "prior_violations": 5,
                    "payment_linked": False,
                    "verified_badge": False,
                    "country_code": "IN",
                    "posting_frequency_per_day": 0.4,
                },
                "ground_truth_decision": "remove",
                "ground_truth_rule": "IT_2021_3_1_j",
            },
            {
                "content_id": "cs_2",
                "text": "School annual day photos posted by verified school account with parent consent notice.",
                "english_summary": "Legitimate school event content, no exploitative context.",
                "content_type": "image_with_caption",
                "sgi_flag": False,
                "upi_pattern_detected": False,
                "toxicity_score": 0.0,
                "language": "en",
                "timestamp_offset_sec": 12,
                "evidence_signals": [],
                "account_meta": {
                    "account_age_days": 1320,
                    "prior_violations": 0,
                    "payment_linked": True,
                    "verified_badge": True,
                    "country_code": "IN",
                    "posting_frequency_per_day": 1.1,
                },
                "ground_truth_decision": "approve",
                "ground_truth_rule": "",
            },
            {
                "content_id": "cs_3",
                "text": "Audio room host instructs minors to share live location for a meetup with gifts.",
                "english_summary": "Child grooming attempt with location solicitation.",
                "content_type": "audio_transcript",
                "sgi_flag": False,
                "upi_pattern_detected": False,
                "toxicity_score": 0.88,
                "language": "hi-en",
                "timestamp_offset_sec": 24,
                "evidence_signals": ["minor_targeting", "location_solicitation"],
                "account_meta": {
                    "account_age_days": 20,
                    "prior_violations": 2,
                    "payment_linked": False,
                    "verified_badge": False,
                    "country_code": "IN",
                    "posting_frequency_per_day": 2.6,
                },
                "ground_truth_decision": "remove",
                "ground_truth_rule": "IT_2021_3_1_j",
            },
            {
                "content_id": "cs_4",
                "text": "NGO campaign post: report child abuse at 1098 and follow verified safety resources.",
                "english_summary": "Public safety awareness content; should remain up.",
                "content_type": "text",
                "sgi_flag": False,
                "upi_pattern_detected": False,
                "toxicity_score": 0.0,
                "language": "en",
                "timestamp_offset_sec": 36,
                "evidence_signals": [],
                "account_meta": {
                    "account_age_days": 2000,
                    "prior_violations": 0,
                    "payment_linked": True,
                    "verified_badge": True,
                    "country_code": "IN",
                    "posting_frequency_per_day": 0.8,
                },
                "ground_truth_decision": "approve",
                "ground_truth_rule": "",
            },
        ],
    },
}


TASK_ORDER: List[str] = [
    "upi-scam-triage",
    "sgi-compliance-review",
    "cib-graph-takedown",
    "child-safety-escalation",
]
